local opts = {noremap=true, silent=true}

function buf_set_keymap(...)
	vim.api.nvim_set_keymap(...)
end

buf_set_keymap('n', '<leader>b', '<cmd>Telescope buffers<CR>', opts)
buf_set_keymap('n', '<leader>e', '<cmd>Telescope diagnostics<CR>', opts)
buf_set_keymap('n', '<leader>E', '<cmd>lua vim.diagnostic.open_float()<CR>', opts)
buf_set_keymap('n', '<leader>f', '<cmd>Telescope find_files<CR>', opts)
buf_set_keymap('n', '<leader>F', '<cmd>Telescope oldfiles<CR>', opts)
buf_set_keymap('n', '<leader>g', '<cmd>Telescope live_grep<CR>', opts)
buf_set_keymap('n', '<leader>G', '<cmd>Telescope current_buffer_fuzzy_find<CR>', opts)
buf_set_keymap('n', '<leader>d', '<cmd>lua vim.lsp.buf.hover()<CR>', opts)
buf_set_keymap('n', '<leader>D', '<cmd>lua vim.lsp.buf.declaration()<CR>', opts)
buf_set_keymap('n', '<leader>q', '<cmd>q<CR>', opts)
buf_set_keymap('n', '<leader>Q', '<cmd>qa<CR>', opts)
buf_set_keymap('n', '<leader>r', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
buf_set_keymap('n', '<leader>R', '<cmd>Telescope lsp_references<CR>', opts)
buf_set_keymap('n', '<leader>s', '<cmd>Telescope lsp_document_symbols<CR>', opts)
buf_set_keymap('n', '<leader>S', '<cmd>Telescope lsp_dynamic_workspace_symbols<CR>', opts)
buf_set_keymap('n', '<leader>w', '<cmd>w<CR>', opts)
buf_set_keymap('n', '<leader>tt', '<cmd>Telescope<CR>', opts)
buf_set_keymap('n', '(', '<cmd>lua vim.diagnostic.goto_prev()<CR>', opts)
buf_set_keymap('n', ')', '<cmd>lua vim.diagnostic.goto_next()<CR>', opts)

buf_set_keymap('n', '<leader>1', '<cmd>BufferLineGoToBuffer 1<CR>', opts)
buf_set_keymap('n', '<leader>2', '<cmd>BufferLineGoToBuffer 2<CR>', opts)
buf_set_keymap('n', '<leader>3', '<cmd>BufferLineGoToBuffer 3<CR>', opts)
buf_set_keymap('n', '<leader>4', '<cmd>BufferLineGoToBuffer 4<CR>', opts)
buf_set_keymap('n', '<leader>5', '<cmd>BufferLineGoToBuffer 5<CR>', opts)
buf_set_keymap('n', '<leader>6', '<cmd>BufferLineGoToBuffer 6<CR>', opts)
buf_set_keymap('n', '<leader>7', '<cmd>BufferLineGoToBuffer 7<CR>', opts)
buf_set_keymap('n', '<leader>8', '<cmd>BufferLineGoToBuffer 8<CR>', opts)
buf_set_keymap('n', '<leader>9', '<cmd>BufferLineGoToBuffer 9<CR>', opts)
buf_set_keymap('n', '<leader>n', '<cmd>BufferLineCycleNext<CR>', opts)
buf_set_keymap('n', '<leader>p', '<cmd>BufferLineCyclePrev<CR>', opts)

buf_set_keymap('n', '<space>', '<cmd>NvimTreeToggle<CR>', opts)
buf_set_keymap('i', 'jj', '<ESC>', opts)
